name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 */6 * * *" # run every 6 hours

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: giancarlosmendes/giancarlosmendes # optional
          ## content
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          ## commit
          COMMIT_MESSAGE: docs: atualiza `README.md`